apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workshop-gitops-vms-hml

namePrefix: hml-

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/accessCredentials/0/sshPublicKey/source/secret/secretName
        value: hml-workshop-ssh-key
    target:
      kind: VirtualMachine
  - patch: |-
      - op: replace
        path: /spec/to/name
        value: hml-vm-web-service
      - op: add
        path: /spec/host
        value: hml-workshop-vms.apps.joe-quimby.chiarettolabs.com.br
    target:
      kind: Route
      name: vm-web-route
